// PraskForce1 — Credentials Vault → .env.local export
//
// Development-only API route. Accepts a POST body containing the
// decrypted vault contents (portal credentials) plus config values
// (Supabase URL + keys, Anthropic API key, etc.) and writes them to
// .env.local in the repo root. The runner then sources that file
// and has everything it needs to run scrapers against credentialed
// portals.
//
// SECURITY NOTES:
// - This route 404s outside of development (NODE_ENV !== 'development').
//   In production it simply doesn't exist. That's the security model.
// - Writes ONLY to `.env.local` in the project root — path is not
//   user-controlled.
// - Never logs credential values.
// - The decrypted vault is sent over localhost HTTP — safe in dev
//   mode, but this file should never be reachable from a deployed
//   instance.

import { writeFile } from 'fs/promises'
import path from 'path'

function isDev() {
  return process.env.NODE_ENV === 'development'
}

// Escape a value for shell dotenv format. Wraps in double quotes if
// the value contains spaces, = signs, or newlines; escapes embedded
// quotes and backslashes.
function escapeEnvValue(v) {
  if (v == null) return ''
  const s = String(v)
  if (s === '') return ''
  if (/[\s="'\\$#]/.test(s)) {
    return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
  }
  return s
}

// Convert a portal_id into an env var name prefix.
// "mb_civic" → "PF1_MB_CIVIC"
// "property_reports" → "PF1_PROPERTY_REPORTS"
// "zillow_sold" → "PF1_ZILLOW_SOLD"
function portalIdToEnvPrefix(portalId) {
  return 'PF1_' + String(portalId).toUpperCase().replace(/[^A-Z0-9]/g, '_')
}

function buildEnvFile({ supabase, ai, credentials, portals }) {
  const lines = []
  lines.push('# Auto-generated by PraskForce1 — do not edit by hand.')
  lines.push(`# Regenerated on ${new Date().toISOString()}`)
  lines.push('# Source: Configuration → Credentials → "Export to .env.local"')
  lines.push('')

  // Supabase
  lines.push('# ── Supabase ─────────────────────────────────────')
  if (supabase?.url) lines.push(`NEXT_PUBLIC_SUPABASE_URL=${escapeEnvValue(supabase.url)}`)
  if (supabase?.anon_key) lines.push(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${escapeEnvValue(supabase.anon_key)}`)
  if (supabase?.service_role_key) lines.push(`SUPABASE_SERVICE_ROLE_KEY=${escapeEnvValue(supabase.service_role_key)}`)
  lines.push('')

  // Anthropic (Claude API) — used for meeting recap drafting
  if (ai?.api_key) {
    lines.push('# ── Claude API ──────────────────────────────────')
    lines.push(`ANTHROPIC_API_KEY=${escapeEnvValue(ai.api_key)}`)
    if (ai.model) lines.push(`ANTHROPIC_MODEL=${escapeEnvValue(ai.model)}`)
    lines.push('')
  }

  // Portal credentials — one USERNAME/PASSWORD pair per vault entry,
  // named by portal_id. Only portals that appear in both the vault
  // AND the config get exported (safeguards against stale entries).
  const portalById = {}
  for (const p of (portals || [])) portalById[p.id] = p

  const portalCreds = (credentials || []).filter(c => c.portal_id && portalById[c.portal_id])
  if (portalCreds.length > 0) {
    lines.push('# ── Portal credentials ──────────────────────────')
    for (const c of portalCreds) {
      const prefix = portalIdToEnvPrefix(c.portal_id)
      const portal = portalById[c.portal_id]
      lines.push(`# ${portal.name}`)
      if (c.username) lines.push(`${prefix}_USERNAME=${escapeEnvValue(c.username)}`)
      if (c.password) lines.push(`${prefix}_PASSWORD=${escapeEnvValue(c.password)}`)
      if (c.url && c.url !== portal.url) lines.push(`${prefix}_URL=${escapeEnvValue(c.url)}`)
      lines.push('')
    }
  }

  // Any other vault entries (e.g. services not in the portals list —
  // StoneProfits, Outlook, etc.) get exported with a generic PF1_ prefix
  // so the runner can still reach them.
  const otherCreds = (credentials || []).filter(c => c.portal_id && !portalById[c.portal_id])
  if (otherCreds.length > 0) {
    lines.push('# ── Other services ──────────────────────────────')
    for (const c of otherCreds) {
      const prefix = portalIdToEnvPrefix(c.portal_id)
      if (c.label) lines.push(`# ${c.label}`)
      if (c.username) lines.push(`${prefix}_USERNAME=${escapeEnvValue(c.username)}`)
      if (c.password) lines.push(`${prefix}_PASSWORD=${escapeEnvValue(c.password)}`)
      if (c.url) lines.push(`${prefix}_URL=${escapeEnvValue(c.url)}`)
      lines.push('')
    }
  }

  return lines.join('\n') + '\n'
}

export async function POST(request) {
  if (!isDev()) {
    return new Response('Not found', { status: 404 })
  }

  let body
  try {
    body = await request.json()
  } catch {
    return Response.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const { supabase, ai, credentials, portals } = body || {}
  if (!Array.isArray(credentials) && !supabase && !ai) {
    return Response.json({
      error: 'Nothing to export. Provide at least one of: supabase, ai, credentials.',
    }, { status: 400 })
  }

  const envContent = buildEnvFile({ supabase, ai, credentials, portals })
  const envPath = path.join(process.cwd(), '.env.local')

  try {
    await writeFile(envPath, envContent, { encoding: 'utf8', mode: 0o600 })
  } catch (e) {
    return Response.json({
      error: `Failed to write .env.local: ${e.message}`,
    }, { status: 500 })
  }

  // Count what got written for the UI to report. Never log values.
  const portalCount = (credentials || []).filter(c => c.portal_id).length
  return Response.json({
    ok: true,
    path: envPath,
    bytes: Buffer.byteLength(envContent, 'utf8'),
    portal_credentials_written: portalCount,
    has_supabase_url: !!supabase?.url,
    has_supabase_anon: !!supabase?.anon_key,
    has_supabase_service_role: !!supabase?.service_role_key,
    has_anthropic_key: !!ai?.api_key,
  })
}

export async function GET() {
  if (!isDev()) return new Response('Not found', { status: 404 })
  return Response.json({
    ok: true,
    note: 'POST to this route with { supabase, ai, credentials, portals } to write .env.local.',
  })
}
